### ISSUE TITLE
Issue on your file - our code does not work

### ISSUE THREAD

**Issue by digitalarche** [sreedharande/Microsoft-Sentinel-As-A-Code#1]
I list here : 

1 - You declare in your main Function this line: 
$FolderName = Get-FolderName -initialDirectory $CurrentLoation.Drive.Root but as you will see an error of Type $CurrentLoation at the link of $CurrentLocation

2 - But moreover even if you correct this Variable it is not declared anywhere. 

3 - Finally, I think it would be good if you really indicated that you are using Powershell 7.x and not 5.x and above because some of the functions used do not have the parameters declared in 5.x as in one of your helper functions you use :
ConvertTo-Json -Depth 10 -EnumsAsStrings But -EnumsAsStrings exists only in Powershell 7.x (6.x perhaps) 

Here you go, I hope this will be useful and make your script runnable. 
See you soon. 
Franck.

**Comment by sreedharande** [comment]
@digitalarche - Thanks for trying out and bringing these issues. Now its fixed. Please try
