### ISSUE TITLE
Fixed ResourceGroup "admin" when exporting workbooks

### ISSUE THREAD

**Issue by acd84** [sreedharande/Microsoft-Sentinel-As-A-Code#10]
The workbook export it's not working by default because there's no variable for the resource group select at the code.

Please, check the syntax and add the right variable:

`$BaseUri = "https://management.azure.com/subscriptions/" + $CurrentSubscription.id + "/resourcegroups/admin"`

In the meantime, changing manually the resource group is successful.

Thank you!

**Comment by sreedharande** [comment]
Fixed
