### ISSUE TITLE
Module updating

### ISSUE THREAD

**Issue by ThijsLecomte** [sreedharande/Microsoft-Sentinel-As-A-Code#5]
I think something is broken when asking to update the modules. I have run the script multiple times. and it says it is installs the different modules. But nothing seem to happen

![image](https://user-images.githubusercontent.com/42153270/158332154-65dae514-053d-4f1a-85a6-0418a1b3fd02.png)

**Comment by sreedharande** [comment]
@ThijsLecomte - This issue has been fixed. Please get latest and let me know if you have any issues
