### ISSUE TITLE
Remove hardcoded resource references

### ISSUE THREAD

**Issue by ThijsLecomte** [sreedharande/Microsoft-Sentinel-As-A-Code#6]
When working with CI/CD, having a hardcoded subscriptionID, Resouce Group & Resource Name  is a deal breaker. Can these be updated to parameters?

**Comment by sreedharande** [comment]
@ThijsLecomte - Do you mean in the Generated ARM Template?? Can you please elaborate

**Comment by ThijsLecomte** [comment]
Yes, within the generated ARM template you have the ResourceID hardcoded with contain the subscription ID, resource group etc. These should be removed as within DevOps, you mostly deploy to another resource

**Comment by sreedharande** [comment]
@ThijsLecomte - Thanks for quick response. I was able to see in Automation Rules - Will fix it

**Comment by sreedharande** [comment]
@ThijsLecomte - fixed
